blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .feeds import LatestEntriesFeed
from .sitemap import (
    PostSitemap, TagSitemap,
    CategorySitemap, StaticSitemap
)
app_name = 'blog'

sitemaps = {
    'post': PostSitemap,
    'category': CategorySitemap,
    'tag': TagSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),

    path('ping/', views.ping, name='ping'),

    path('alltag/', views.TagListView.as_view(), name='tag_list'),

    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),

    path('tag/<str:tag>/', views.TagView.as_view(), name='tag'),

    path('contact/', views.ContactMeCreateView.as_view(), name='contact'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('contact_mail/', views.ContactMailListView.as_view(), name='contact_mail'),
    path('contact_mail/<int:pk>', views.ContactMailDetailView.as_view(), name='contact_mail_detail'),

    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
    path('recomment/<int:pk>/', views.ReCommentCreateView.as_view(), name='recomment'),
    path('file_download/<int:pk>/', views.file_download, name='file_download'),

    path('private/', views.PostPrivateIndexView.as_view(), name='private'),

    path('latest/feed/', LatestEntriesFeed(), name='feed'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

core/urls.py
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path('home', views.home, name='home'),
    path('home/<int:community_id>/', views.real_home, name='real_home'),
    path('home/<int:community_id>/article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('home/<int:community_id>/article/<int:article_id>/edit', views.article_edit, name='article_edit'),
    path('article/<int:article_id>/delete', views.article_delete, name='article_delete'),
    path('home/<int:community_id>/create/', views.article_create, name='article_create'),

    path('home/article/<int:article_id>/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),

    path('my_article/', views.my_article, name='my_article'),

    path('community_manage/', views.community_manage, name='community_manage'),
    path('community_create/', views.community_create, name='community_create'),
    path('home/<int:community_id>/detail/', views.community_detail, name='community_detail'),
    path('home/<int:community_id>/edit/', views.community_edit, name='community_edit'),
    path('home/<int:community_id>/delete/', views.community_delete, name='community_delete'),

    path('community_search/', views.community_search, name='community_search'),
    path('home/<int:community_id>/follow', views.community_follow, name='community_follow'),
    path('home/<int:community_id>/user_manage/', views.community_user_manage, name='community_user_manage'),
    path('home/<int:community_id>/permitted_user_manage/', views.community_permitted_user_manage,
         name='community_permitted_user_manage'),
]

curation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import login, logout
from user_auth.views import signup, my_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),

    path('login/', login, kwargs={'template_name': 'user_auth/login.html'}, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
    path('my_page/', my_page, name='my_page'),
]

# 開発環境でのメディアファイルの配信設定
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

blog/models.py
import os
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.db import models
from django.utils import timezone


# サイト詳細情報のテーマカラーの選択肢
SITE_COLORS = (
    ('primary', '青色'),
    ('secondary', '灰色'),
    ('success', '緑色'),
    ('info', '水色'),
    ('warning', '黄色'),
    ('danger', '赤'),
    ('dark', '黒'),
)

DEFAULT_HEADER_TEXT = "paleolithic !!"


class Category(models.Model):
    """category"""
    name = models.CharField(max_length=255)

    def __str__(self):
        """ str. """
        return self.name


class Tag(models.Model):
    """ tag """
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField('本文')
    category = models.ForeignKey(Category, verbose_name="カテゴリー", on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, blank=True, verbose_name="タグ")
    thumbnail = models.ImageField('サムネイル', upload_to='post_thumbnail/%Y/%m/%d/', blank=True, null=True)
    is_public = models.BooleanField('公開可否', default=True)
    friend_posts = models.ManyToManyField('self', verbose_name="関連記事", blank=True)
    description = models.TextField('記事の説明', blank=True)
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.title

    def get_description(self):
        if self.description:
            return self.description
        else:
            description = "カテゴリ：{0}, タグ：{1}"
            category = self.category
            tags = ' '.join(tag.name for tag in self.tag.all())
            description = description.format(category, tags)
            return description

    def get_text(self):
        if len(self.text) >= 100:
            return self.text[:100] + '...'
        else:
            return self.text

    def get_next(self):
        """次の記事を取得する(日付)
        パフォーマンス的に、無駄が多い処理ですが、APIとして一応残しておきます。
        """
        next_post = Post.objects.filter(is_public=True, created_at__gt=self.created_at).order_by('-created_at')
        if next_post:
            return next_post.last()
        return None

    def get_prev(self):
        """前の記事を取得する(日付)
        パフォーマンス的に、無駄が多い処理ですが、APIとして一応残しておきます。
        """
        prev_post = Post.objects.filter(is_public=True, created_at__lt=self.created_at).order_by('-created_at')
        if prev_post:
            return prev_post.first()
        return None


class ContactMail(models.Model):
    """ contact mail"""
    name = models.CharField('名前', max_length=30)
    email = models.EmailField('Email')
    text = models.TextField('内容')
    created_at = models.DateTimeField('作成日', auto_now_add=True)

    def get_text(self):
        if len(self.text) >= 30:
            return self.text + '...'
        else:
            return self.text


class Comment(models.Model):
    """ comment """
    name = models.CharField('名前', max_length=20, default='名無し')
    text = models.TextField('コメント')
    icon = models.ImageField('サムネイル', upload_to='comment_thumbnail/%Y/%m/%d/', blank=True, null=True)
    target = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='対象記事')
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', auto_now_add=True)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.file.url)


class ReComment(models.Model):
    """ reComment"""
    name = models.CharField('名前', max_length=20, default='名無し')
    text = models.TextField('返信')
    icon = models.ImageField('サムネイル', upload_to='recomment_thumbnail/%Y/%m/%d/', blank=True, null=True)
    target = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='対象コメント')
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', auto_now_add=True)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """ get filename"""
        return os.path.basename(self.file.url)


class Link(models.Model):
    """link"""
    name = models.CharField('リンク', max_length=255)
    adrs = models.CharField('アドレス', max_length=255)

    def __str__(self):
        return self.name


class Analytics(models.Model):
    """アナリティクスの情報"""
    name = models.CharField('アナリティクス', max_length=255, blank=True)
    html = models.TextField('アナリティクスHTML', blank=True)

    def __str__(self):
        return self.name


class Ads(models.Model):
    """広告関連"""
    name = models.CharField('広告名', max_length=255, blank=True)
    html = models.TextField('広告HTML', blank=True)

    def __str__(self):
        return self.name


class SiteDetail(models.Model):
    """サイトの詳細情報"""
    site = models.OneToOneField(Site, verbose_name='Site', on_delete=models.PROTECT)
    title = models.CharField('タイトル', max_length=255, default='タイトル')
    heaer_text = models.TextField('ヘッダーテキスト', max_length=255, default=DEFAULT_HEADER_TEXT)
    description = models.TextField('サイト説明', max_length=255, default="説明")
    author = models.CharField('管理人', max_length=255, default='muscle')
    author_mail = models.EmailField('メールアドレス', default="muscle@gmail.com")
    color = models.CharField('サイトテーマ色', choices=SITE_COLORS, default='primary', max_length=30)

    def __str__(self):
        return self.author


class PopularPost(models.Model):
    """人気記事"""
    title = models.CharField('タイトル', max_length=255)
    url = models.CharField('URL', max_length=255)
    page_view = models.ImageField('ページビュー数')

    def __str__(self):
        return "{} {} {}".format(self.url, self.title, self.page_view)


class Image(models.Model):
    """image file related to post"""
    title = models.CharField('タイトル', max_length=255)
    post = models.ForeignKey(Post, on_delete=models.PROTECT, verbose_name='記事')
    src = models.ImageField('画像', upload_to='images/%Y/%m/%d/', help_text='送信後、一度保存してください')
    created_at = models.DateTimeField('作成日', auto_now=True)

    def __str__(self):
        return '間接リンク:[filter imgpk]{0}[end] 直接リンク:[filter img]{1}[end]'.format(self.pk, self.src.url)


class File(models.Model):
    """記事やコメントに紐づく添付ファイル"""
    title = models.CharField('タイトル', max_length=255, blank=True)
    src = models.FileField('添付ファイル', upload_to='files/%Y/%m/%d/')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return 'モデル:{} pk:{} url:{}'.format(self.content_type, self.object_id, self.src.url)

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.src.url)

blog/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sitemaps import ping_google
from django.urls import reverse_lazy
from django.db.models import Q, Count
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views import generic
from .forms import PostSearchForm, CommentCreateForm, ReCommentCreateForm, FileInlineFormSet, ContactMeCreateForm
from .models import Post, Comment, Tag, Category, ReComment, File, ContactMail


class BaseListView(generic.ListView):
    """記事の一覧表示の基底クラス"""
    paginate_by = 10

    def get_queryset(self):
        """公開フラグがTrue、作成日順の記事を返す"""
        # post.categoryや、post.tag.allをテンプレートで書く場合は
        # それぞれselect_relatedやprefetch_relatedで改善できる場合があります。
        query_set = Post.objects.filter(
            is_public=True
        ).order_by('-created_at').select_related('category').prefetch_related('tag')
        return query_set


class PostIndexView(BaseListView):
    """トップページ"""

    def get_queryset(self):
        """クイックサーチの絞り込み"""
        global_form = PostSearchForm(self.request.GET)
        global_form.is_valid()
        keyword = global_form.cleaned_data['keyword']
        queryset = super().get_queryset()

        if keyword:
            for word in keyword.split():
                queryset = queryset.filter(
                    Q(title__icontains=word) | Q(text__icontains=word)
                )
        return queryset


class PostPrivateIndexView(LoginRequiredMixin, BaseListView):
    """非公開の記事一覧"""

    def get_queryset(self):
        """公開フラグがFalse、作成日順"""
        queryset = Post.objects.filter(
            is_public=False
        ).order_by('-created_at').select_related('category').prefetch_related('tag')
        return queryset


class CategoryView(BaseListView):
    """click link of categories"""

    def get_queryset(self):
        """カテゴリの絞り込み"""
        category_name = self.kwargs['category']
        self.category = Category.objects.get(name=category_name)
        query_set = super().get_queryset().filter(category=self.category)
        return query_set

    def get_context_data(self, *args, **kwargs):
        """クリックされたカテゴリを保持"""
        context = super().get_context_data(*args, **kwargs)
        context['category'] = self.category
        return context


class TagView(BaseListView):
    """タグのリンククリック"""

    def get_queryset(self):
        tag_name = self.kwargs['tag']
        self.tag = Tag.objects.get(name=tag_name)
        query_set = super().get_queryset().filter(tag=self.tag)
        return query_set

    def get_context_data(self, *args, **kwargs):
        """クリックされたタグを保持"""
        context = super().get_context_data(*args, **kwargs)
        context['tag'] = self.tag
        return context


class PostDetailView(generic.DetailView):
    """記事詳細ページ"""
    model = Post

    def get_object(self, query_set=None):
        """その記事が公開か、ユーザがログインしていればよし"""
        post = super().get_object()
        if post.is_public or self.request.user.is_authenticated:
            return post
        else:
            return Http404


class ContactMeCreateView(generic.CreateView):
    """ダイレクトメールを送る画面"""
    form_class = ContactMeCreateForm
    template_name = 'blog/contact_me_form.html'
    success_url = reverse_lazy('blog:thanks')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ThanksView(generic.TemplateView):
    template_name = 'blog/thank.html'


class ContactMailListView(generic.ListView):
    paginate_by = 20
    template_name = 'blog/contact_mail.html'
    context_object_name = 'mail_list'

    def get_queryset(self):
        mail = ContactMail.objects.all().order_by('-created_at')
        return mail


class ContactMailDetailView(generic.DetailView):
    model = ContactMail
    template_name = 'blog/contact_mail_detail.html'
    context_object_name = 'mail'

    def get_object(self, query_set=None):
        mail = super().get_object()
        if self.request.user.is_authenticated:
            return mail
        else:
            return Http404


class CommentCreateView(generic.CreateView):
    """コメント投稿画面
    '^comment/(?P<pk>[0-9]+)/$'のようにして、記事のpkも受け取っている
    このpkをcontextへ渡し前へ戻るリンクに利用したり、targetに指定する記事を取得するのに使う
    """
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        """記事をコメントのターゲットに指定"""
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.target = Post.objects.get(id=post_pk)
        comment.save()
        formset = FileInlineFormSet(self.request.POST, instance=comment, files=self.request.FILES)
        if formset.is_valid():
            formset.save()
        return redirect('blog:detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        if 'formset' not in context:
            context['formset'] = FileInlineFormSet(self.request.POST or None)
        return context


class ReCommentCreateView(generic.CreateView):
    """返信コメント投稿"""

    model = ReComment
    form_class = ReCommentCreateForm
    template_name = 'blog/comment_form.html'

    def form_valid(self, form):
        comment_pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=comment_pk)
        recomment = form.save(commit=False)
        recomment.target = comment
        recomment.save()

        formset = FileInlineFormSet(self.request.POST, instance=recomment, files=self.request.FILES)
        if formset.is_valid():
            formset.save()
        return redirect('blog:detail', pk=comment.target.pk)

    def get_context_data(self, **kwargs):
        comment_pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=comment_pk)
        context = super().get_context_data(**kwargs)
        context['post'] = comment.target
        if 'formset' not in context:
            context['formset'] = FileInlineFormSet(self.request.POST or None)
        return context


class TagListView(generic.ListView):
    """タグの一覧ビュー"""

    model = Tag
    queryset = Tag.objects.annotate(
        num_posts=Count('post')).order_by('-num_posts')


@login_required
def ping(request):
    """Googleにpingを送信する"""
    try:
        url = reverse_lazy('blog:sitemap')
        ping_google(sitemap_url=url)
    except Exception:
        raise
    else:
        return redirect('blog:index', permanent=True)


def file_download(request, pk):
    """コメントに添付されたファイルのダウンロード
    ユーザーがアップロードできるファイルなので、セキュリティ対策のため
    必ずブラウザ上で開かせず、ダウンロードさせるようにする
    """
    file = get_object_or_404(File, pk=pk)
    response = HttpResponse(file.src, content_type='application/octet-stream')
    response['Content-Disposition'] = 'attachment; filename="{}"'.format(file.get_filename())
    return response

blog/templates/blog/widgets/detail_card.html
{% load blogfilter %}
{% load static %}
<style>
    pre.prettyprint {
      white-space: pre;
    }
    .prettyprint ol.linenums > li {
      list-style-type: decimal; 
    }
</style>
<div class="card">
  <div class="card-header " style="background: #6c757d;">
    <h1 class="card-title text-white">{{ post.title }}</h1>
  </div>
  
  <div class="card-body">
      <span class="badge  badge-pill" style="background: #6c757d;">{% by_the_time post.created_at %}</span>
      <span class="badge  badge-pill" style="background: #6c757d;">{{ post.created_at }}</span>
      <br>
  
      <span class="badge" style="background: #6c757d;">
        <a class="text-white" href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a>
      </span>
      <br>
  
      {% for tag in post.tag.all %}
        <span class="badge" style="background: #6c757d">
          <a class="text-white" href="{% url 'blog:tag' tag.name %}">{{ tag.name }}</a>
        </span>
      {% endfor %}
      <hr>
  
      {% if user.is_authenticated %}
        <a href="{% url 'admin:blog_post_change' post.pk %}">管理画面へ</a>
        <hr>
      {% endif %}
    
    {{ post.text | linebreaksbr | blog }}
  </div>
  
  <div class="card-footer">
    <p>添付ファイル</p>
    {% for file in post.files.all %}
      <a href="{% url 'blog:file_download' file.pk %}">{{ file.title }} - {{ file.get_filename }}</a><br>
    {% endfor %}
  
    <p>関連記事</p>
    {% for post in post.friend_posts.all %}
      {% if post.is_public %}
          <p><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></p>
      {% endif %}
    {% endfor %}    
  
  </div>
</div>
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?skin=desert"></script>

blog/templates/blog/widgets/detail_comment.html
{% load blogfilter %}
{% load static %}
<div class="row mt-3">
  <div class="col-md-2 d-none d-md-block">
    {% if comment.icon %}
      <img class="img-fluid lazy" data-original="{{ comment.icon.url }}">
    {% else %}
      <img class="img-fluid lazy" data-original="{% static 'blog/img/noimage.png' %}">
    {% endif %}
  </div>
  <div class="col-md-10">
      <h5>
        {{ comment.name }}
        <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time comment.created_at %}</span>
        <span class="badge badge-{{ mysite.color }} badge-pill">{{ comment.created_at }}</span>
        <a href="{% url 'blog:recomment' comment.pk %}">返信する</a>
      </h5>
      {% for file in comment.files.all %}
        <a href="{% url 'blog:file_download' file.pk %}">添付ファイルダウンロード({{ file.get_filename }})</a><br>
      {% endfor %}
      {{ comment.text | linebreaksbr }}
      <!-- 返信コメント -->
      {% for recomment in comment.recomment_set.all %}
        <div class="row mt-3">
          <div class="col-md-2 d-none d-md-block">
            {% if recomment.icon %}
              <img class="img-fluid lazy" data-original="{{ recomment.icon.url }}">
            {% else %}
              <img class="img-fluid lazy" data-original="{% static 'blog/img/noimage.png' %}">
            {% endif %}
          </div>
          <div class="col-md-10">
              <h5>
                {{ recomment.name }}
                <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time recomment.created_at %}</span>
                <span class="badge badge-{{ mysite.color }} badge-pill">{{ recomment.created_at }}</span>
              </h5>
              {% for file in recomment.files.all %}
                <a href="{% url 'blog:file_download' file.pk %}">添付ファイルダウンロード({{ file.get_filename }})</a><br>
              {% endfor %}
              {{ recomment.text | linebreaksbr }}
        
          </div>
        </div>
      {% endfor %}
      <!-- 返信コメントおわり -->
  </div>
</div>

blog/templates/blog/widgets/list_card.html
{% load blogfilter %}
{% load static %}

<div class="mb-3 card">

    {#  <div class="card-header">#}
    {#    <h1 class="card-title text-white">{{ post.title }}</h1>#}
    {#  </div><!-- card-header終了 -->#}

    <div class="card-body row">
        <!-- card-bodyの左側 -->
        <div class="col-xs-12 col-sm-6 text-center">
            {% if post.thumbnail %}
                <a href="{{ post.thumbnail.url }}" target="_blank" rel="nofollow"><img class="img-fluid lazy"
                                                                                       data-original="{{ post.thumbnail.url }}"
                                                                                       alt="{{ post.title }}"></a>
            {% else %}
                <img class="img-fluid lazy" data-original="{% static 'blog/img/noimage.png' %}" alt="{{ post.title }}">
            {% endif %}
        </div><!-- card-bodyの左側終わり -->

        <!-- card-bodyの右側 -->
        <div class="col-xs-12 col-sm-6" style="position: relative">
            <h1 class="">{{ post.title }}</h1>
            <hr/>
            {#      <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time post.created_at %}</span>#}
            {#      <span class="badge badge-{{ mysite.color }} badge-pill">{{ post.created_at }}</span>#}
            {#      <br>#}

            <span class="badge badge-info">
        <a class="text-white" href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a>
      </span>
            <br>

            {% for tag in post.tag.all %}
                <span class="badge badge-secondary">
          <a class="text-white" href="{% url 'blog:tag' tag.name %}">{{ tag.name }}</a>
        </span>
            {% endfor %}
            <hr>

            {#            <a class="btn btn-outline-info btn-lg btn-block"#}
            {#               href="{% url 'blog:detail' post.pk %}">続きを読む</a>#}
            {#            <br>#}
            <p><a class="text-secondary" href="{% url 'blog:detail' post.pk %}">{{ post.get_description }}</a></p>


            <br/>
            <div style="position: absolute; bottom: 0;">
                {% if user.is_authenticated %}
                    <a href="{% url 'admin:blog_post_change' post.pk %}">管理画面へ</a>
                {% endif %}
                <p class="text-secondary " >{{ post.created_at }}</p>
            </div>
        </div><!-- card-bodyの右側おわり -->

    </div><!-- card-body終了 -->

</div>
{#<div class="row align-items-center">#}
{#    <div class="col-12 col-md-6">#}
{#        <div class="single-blog-thumbnail">#}
{#            <img src="img/blog-img/3.jpg" alt="" title="" style="">#}
{#            <div class="post-date">#}
{#                <a href="#">12 <span>march</span></a>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#    <div class="col-12 col-md-6">#}
{#        <!-- Blog Content -->#}
{#        <div class="single-blog-content">#}
{#            <div class="line"></div>#}
{#            <a href="#" class="post-tag">Lifestyle</a>#}
{#            <h4><a href="#" class="post-headline">Party people in the house</a></h4>#}
{#            <p>Curabitur venenatis efficitur lorem sed tempor. Integer aliquet tempor cursus. Nullam vestibulum#}
{#                convallis risus vel condimentum. Nullam auctor lorem in libero luctus, vel volutpat quam tincidunt.</p>#}
{#            <div class="post-meta">#}
{#                <p>By <a href="#">james smith</a></p>#}
{#                <p>3 comments</p>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

blog/templates/blog/widgets/nav.html
<nav class="navbar navbar-expand-lg navbar-dark " style="background: #23272b">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto ml-sm-5">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:tag_list' %}">All Tag</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" target="_blank" href="{% url 'blog:feed' %}" rel="nofollow">Feed</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:private' %}" rel="nofollow">Private</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" target="_blank" href="{% url 'admin:index' %}" rel="nofollow">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:ping' %}" rel="nofollow">Ping</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:home' %}" rel="nofollow">Curation</a>
            </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'blog:index' %}">
          {{ global_form.keyword }}
{#          <button class="btn my-2 my-sm-0" type="submit">検索</button>#}
        </form>
      </div>
    </div>
</nav>

blog/templates/blog/widgets/side_about.html
{% load static %}
<div class="card">
    <div class="card-header" style="background: #6c757d;">
        <h3 class="card-title text-left text-white">About</h3>
    </div>

    <div class="card-body">
        <img class="img-fluid lazy" src="{% static 'blog/img/side_about_icon.png' %}">
        <p class="mb-3">こんにちわ</p>
        <a class="btn btn-dark d-block mx-auto mb-2" href="{% url 'blog:contact' %}">Contact Me</a>
        {% if user.is_authenticated %}
            <a class="btn btn-light d-block mx-auto" href="{% url 'blog:contact_mail' %}">Mail List</a>
        {% endif %}
    </div>

</div>