blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .feeds import LatestEntriesFeed
from .sitemap import (
    PostSitemap, TagSitemap,
    CategorySitemap, StaticSitemap
)
app_name = 'blog'

sitemaps = {
    'post': PostSitemap,
    'category': CategorySitemap,
    'tag': TagSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),

    path('ping/', views.ping, name='ping'),

    path('alltag/', views.TagListView.as_view(), name='tag_list'),

    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),

    path('tag/<str:tag>/', views.TagView.as_view(), name='tag'),

    path('contact/', views.ContactMeCreateView.as_view(), name='contact'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('contact_mail/', views.ContactMailListView.as_view(), name='contact_mail'),
    path('contact_mail/<int:pk>', views.ContactMailDetailView.as_view(), name='contact_mail_detail'),

    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
    path('recomment/<int:pk>/', views.ReCommentCreateView.as_view(), name='recomment'),
    path('file_download/<int:pk>/', views.file_download, name='file_download'),

    path('private/', views.PostPrivateIndexView.as_view(), name='private'),

    path('latest/feed/', LatestEntriesFeed(), name='feed'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

curation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import login, logout
from user_auth.views import signup, my_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),

    path('login/', login, kwargs={'template_name': 'user_auth/login.html'}, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
    path('my_page/', my_page, name='my_page'),
]

# 開発環境でのメディアファイルの配信設定
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

blog/models.py
import os
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.db import models
from django.utils import timezone


# サイト詳細情報のテーマカラーの選択肢
SITE_COLORS = (
    ('primary', '青色'),
    ('secondary', '灰色'),
    ('success', '緑色'),
    ('info', '水色'),
    ('warning', '黄色'),
    ('danger', '赤'),
    ('dark', '黒'),
)

DEFAULT_HEADER_TEXT = "paleolithic !!"


class Category(models.Model):
    """category"""
    name = models.CharField(max_length=255)

    def __str__(self):
        """ str. """
        return self.name


class Tag(models.Model):
    """ tag """
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField('本文')
    category = models.ForeignKey(Category, verbose_name="カテゴリー", on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, blank=True, verbose_name="タグ")
    thumbnail = models.ImageField('サムネイル', upload_to='post_thumbnail/%Y/%m/%d/', blank=True, null=True)
    is_public = models.BooleanField('公開可否', default=True)
    friend_posts = models.ManyToManyField('self', verbose_name="関連記事", blank=True)
    description = models.TextField('記事の説明', blank=True)
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.title

    def get_description(self):
        if self.description:
            return self.description
        else:
            description = "カテゴリ：{0}, タグ：{1}"
            category = self.category
            tags = ' '.join(tag.name for tag in self.tag.all())
            description = description.format(category, tags)
            return description

    def get_text(self):
        if len(self.text) >= 100:
            return self.text[:100] + '...'
        else:
            return self.text

    def get_next(self):
        """次の記事を取得する(日付)
        パフォーマンス的に、無駄が多い処理ですが、APIとして一応残しておきます。
        """
        next_post = Post.objects.filter(is_public=True, created_at__gt=self.created_at).order_by('-created_at')
        if next_post:
            return next_post.last()
        return None

    def get_prev(self):
        """前の記事を取得する(日付)
        パフォーマンス的に、無駄が多い処理ですが、APIとして一応残しておきます。
        """
        prev_post = Post.objects.filter(is_public=True, created_at__lt=self.created_at).order_by('-created_at')
        if prev_post:
            return prev_post.first()
        return None


class ContactMail(models.Model):
    """ contact mail"""
    name = models.CharField('名前', max_length=30)
    email = models.EmailField('Email')
    text = models.TextField('内容')
    created_at = models.DateTimeField('作成日', auto_now_add=True)

    def get_text(self):
        if len(self.text) >= 30:
            return self.text + '...'
        else:
            return self.text


class Comment(models.Model):
    """ comment """
    name = models.CharField('名前', max_length=20, default='名無し')
    text = models.TextField('コメント')
    icon = models.ImageField('サムネイル', upload_to='comment_thumbnail/%Y/%m/%d/', blank=True, null=True)
    target = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='対象記事')
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', auto_now_add=True)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.file.url)


class ReComment(models.Model):
    """ reComment"""
    name = models.CharField('名前', max_length=20, default='名無し')
    text = models.TextField('返信')
    icon = models.ImageField('サムネイル', upload_to='recomment_thumbnail/%Y/%m/%d/', blank=True, null=True)
    target = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='対象コメント')
    files = GenericRelation('File')
    created_at = models.DateTimeField('作成日', auto_now_add=True)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """ get filename"""
        return os.path.basename(self.file.url)


class Link(models.Model):
    """link"""
    name = models.CharField('リンク', max_length=255)
    adrs = models.CharField('アドレス', max_length=255)

    def __str__(self):
        return self.name


class Analytics(models.Model):
    """アナリティクスの情報"""
    name = models.CharField('アナリティクス', max_length=255, blank=True)
    html = models.TextField('アナリティクスHTML', blank=True)

    def __str__(self):
        return self.name


class Ads(models.Model):
    """広告関連"""
    name = models.CharField('広告名', max_length=255, blank=True)
    html = models.TextField('広告HTML', blank=True)

    def __str__(self):
        return self.name


class SiteDetail(models.Model):
    """サイトの詳細情報"""
    site = models.OneToOneField(Site, verbose_name='Site', on_delete=models.PROTECT)
    title = models.CharField('タイトル', max_length=255, default='タイトル')
    heaer_text = models.TextField('ヘッダーテキスト', max_length=255, default=DEFAULT_HEADER_TEXT)
    description = models.TextField('サイト説明', max_length=255, default="説明")
    author = models.CharField('管理人', max_length=255, default='muscle')
    author_mail = models.EmailField('メールアドレス', default="muscle@gmail.com")
    color = models.CharField('サイトテーマ色', choices=SITE_COLORS, default='primary', max_length=30)

    def __str__(self):
        return self.author


class PopularPost(models.Model):
    """人気記事"""
    title = models.CharField('タイトル', max_length=255)
    url = models.CharField('URL', max_length=255)
    page_view = models.ImageField('ページビュー数')

    def __str__(self):
        return "{} {} {}".format(self.url, self.title, self.page_view)


class Image(models.Model):
    """image file related to post"""
    title = models.CharField('タイトル', max_length=255)
    post = models.ForeignKey(Post, on_delete=models.PROTECT, verbose_name='記事')
    src = models.ImageField('画像', upload_to='images/%Y/%m/%d/', help_text='送信後、一度保存してください')
    created_at = models.DateTimeField('作成日', auto_now=True)

    def __str__(self):
        return '間接リンク:[filter imgpk]{0}[end] 直接リンク:[filter img]{1}[end]'.format(self.pk, self.src.url)


class File(models.Model):
    """記事やコメントに紐づく添付ファイル"""
    title = models.CharField('タイトル', max_length=255, blank=True)
    src = models.FileField('添付ファイル', upload_to='files/%Y/%m/%d/')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return 'モデル:{} pk:{} url:{}'.format(self.content_type, self.object_id, self.src.url)

    def get_filename(self):
        """ファイル名を取得する"""
        return os.path.basename(self.src.url)

blog/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sitemaps import ping_google
from django.urls import reverse_lazy
from django.db.models import Q, Count
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views import generic
from .forms import PostSearchForm, CommentCreateForm, ReCommentCreateForm, FileInlineFormSet, ContactMeCreateForm
from .models import Post, Comment, Tag, Category, ReComment, File, ContactMail


class BaseListView(generic.ListView):
    """記事の一覧表示の基底クラス"""
    paginate_by = 10

    def get_queryset(self):
        """公開フラグがTrue、作成日順の記事を返す"""
        # post.categoryや、post.tag.allをテンプレートで書く場合は
        # それぞれselect_relatedやprefetch_relatedで改善できる場合があります。
        query_set = Post.objects.filter(
            is_public=True
        ).order_by('-created_at').select_related('category').prefetch_related('tag')
        return query_set


class PostIndexView(BaseListView):
    """トップページ"""

    def get_queryset(self):
        """クイックサーチの絞り込み"""
        global_form = PostSearchForm(self.request.GET)
        global_form.is_valid()
        keyword = global_form.cleaned_data['keyword']
        queryset = super().get_queryset()

        if keyword:
            for word in keyword.split():
                queryset = queryset.filter(
                    Q(title__icontains=word) | Q(text__icontains=word)
                )
        return queryset


class PostPrivateIndexView(LoginRequiredMixin, BaseListView):
    """非公開の記事一覧"""

    def get_queryset(self):
        """公開フラグがFalse、作成日順"""
        queryset = Post.objects.filter(
            is_public=False
        ).order_by('-created_at').select_related('category').prefetch_related('tag')
        return queryset


class CategoryView(BaseListView):
    """click link of categories"""

    def get_queryset(self):
        """カテゴリの絞り込み"""
        category_name = self.kwargs['category']
        self.category = Category.objects.get(name=category_name)
        query_set = super().get_queryset().filter(category=self.category)
        return query_set

    def get_context_data(self, *args, **kwargs):
        """クリックされたカテゴリを保持"""
        context = super().get_context_data(*args, **kwargs)
        context['category'] = self.category
        return context


class TagView(BaseListView):
    """タグのリンククリック"""

    def get_queryset(self):
        tag_name = self.kwargs['tag']
        self.tag = Tag.objects.get(name=tag_name)
        query_set = super().get_queryset().filter(tag=self.tag)
        return query_set

    def get_context_data(self, *args, **kwargs):
        """クリックされたタグを保持"""
        context = super().get_context_data(*args, **kwargs)
        context['tag'] = self.tag
        return context


class PostDetailView(generic.DetailView):
    """記事詳細ページ"""
    model = Post

    def get_object(self, query_set=None):
        """その記事が公開か、ユーザがログインしていればよし"""
        post = super().get_object()
        if post.is_public or self.request.user.is_authenticated:
            return post
        else:
            return Http404


class ContactMeCreateView(generic.CreateView):
    """ダイレクトメールを送る画面"""
    form_class = ContactMeCreateForm
    template_name = 'blog/contact_me_form.html'
    success_url = reverse_lazy('blog:thanks')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ThanksView(generic.TemplateView):
    template_name = 'blog/thank.html'


class ContactMailListView(generic.ListView):
    paginate_by = 20
    template_name = 'blog/contact_mail.html'
    context_object_name = 'mail_list'

    def get_queryset(self):
        mail = ContactMail.objects.all().order_by('-created_at')
        return mail


class ContactMailDetailView(generic.DetailView):
    model = ContactMail
    template_name = 'blog/contact_mail_detail.html'
    context_object_name = 'mail'

    def get_object(self, query_set=None):
        mail = super().get_object()
        if self.request.user.is_authenticated:
            return mail
        else:
            return Http404


class CommentCreateView(generic.CreateView):
    """コメント投稿画面
    '^comment/(?P<pk>[0-9]+)/$'のようにして、記事のpkも受け取っている
    このpkをcontextへ渡し前へ戻るリンクに利用したり、targetに指定する記事を取得するのに使う
    """
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        """記事をコメントのターゲットに指定"""
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.target = Post.objects.get(id=post_pk)
        comment.save()
        formset = FileInlineFormSet(self.request.POST, instance=comment, files=self.request.FILES)
        if formset.is_valid():
            formset.save()
        return redirect('blog:detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        if 'formset' not in context:
            context['formset'] = FileInlineFormSet(self.request.POST or None)
        return context


class ReCommentCreateView(generic.CreateView):
    """返信コメント投稿"""

    model = ReComment
    form_class = ReCommentCreateForm
    template_name = 'blog/comment_form.html'

    def form_valid(self, form):
        comment_pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=comment_pk)
        recomment = form.save(commit=False)
        recomment.target = comment
        recomment.save()

        formset = FileInlineFormSet(self.request.POST, instance=recomment, files=self.request.FILES)
        if formset.is_valid():
            formset.save()
        return redirect('blog:detail', pk=comment.target.pk)

    def get_context_data(self, **kwargs):
        comment_pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=comment_pk)
        context = super().get_context_data(**kwargs)
        context['post'] = comment.target
        if 'formset' not in context:
            context['formset'] = FileInlineFormSet(self.request.POST or None)
        return context


class TagListView(generic.ListView):
    """タグの一覧ビュー"""

    model = Tag
    queryset = Tag.objects.annotate(
        num_posts=Count('post')).order_by('-num_posts')


@login_required
def ping(request):
    """Googleにpingを送信する"""
    try:
        url = reverse_lazy('blog:sitemap')
        ping_google(sitemap_url=url)
    except Exception:
        raise
    else:
        return redirect('blog:index', permanent=True)


def file_download(request, pk):
    """コメントに添付されたファイルのダウンロード
    ユーザーがアップロードできるファイルなので、セキュリティ対策のため
    必ずブラウザ上で開かせず、ダウンロードさせるようにする
    """
    file = get_object_or_404(File, pk=pk)
    response = HttpResponse(file.src, content_type='application/octet-stream')
    response['Content-Disposition'] = 'attachment; filename="{}"'.format(file.get_filename())
    return response

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>

    <meta charset="utf-8">
    <meta name="keywords" content="{% block meta_key %}{% endblock %}">
    <meta name="description" content="{% block meta_des %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block icon %}<link rel="shortcut icon" href="{% static 'blog/img/old_man.ico' %}" />{% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

{#    Now-UI-kit#}
{#    <link rel="stylesheet" href="{% static 'now_ui_kit/css/now-ui-kit.css' %}">#}

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'blog/css/base.css'  %}">

    {% block extracss %}{% endblock %}
    <style>
        ul {
            list-style: none;
        }
    </style>

  </head>
  <body>
    {% block layout %}{% endblock %}

  <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.js"></script>
    <script>
        $(function() {
            $("img.lazy").lazyload({
                threshold:200,
                effect:"fadeIn",
                effect_speed:3000,
            });
        });
    </script>

  <!-- Custom JS -->
  {% block extrajs %}{% endblock %}

  {% block analytics %}
    <!-- アナリティクス -->
      {% for anal in analytics %}
        {{ anal.html | safe }}
      {% endfor %}
    <!-- アナリティクス終わり -->
  {% endblock %}

  </body>
</html>

blog/templates/blog/comment_form.html
{% extends "blog/main_layout.html" %}
{% load static %}
{% load blogfilter %}
{% block meta_des %}コメント投稿ページ - {{ mysite.title }}{% endblock %}
{% block title %}コメント投稿ページ - {{ mysite.title }}{% endblock %}

{% block bread %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">記事一覧</a></li>
            <li class="breadcrumb-item"><a
                    href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></li>
            <li class="breadcrumb-item">コメント</li>
        </ol>
    </nav>
{% endblock %}

{% block content %}
    {{ form.non_field_errors }}
    <form action="" method="POST" enctype='multipart/form-data'>
        {% for field in form %}
            <div class="form-group">
                <p style="color: #ff2727">{{ field.errors }}</p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}<!-- コメント部分のフォーム終わり -->

        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.id }}
            {{ form.non_field_errors }}
            {% for field in form.visible_fields %}
                <div class="form-group">
                    <p style="color: #ff2727">{{ field.errors }}</p>
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}<!-- 1つのファイルフォーム終わり -->

        {% endfor %}<!-- formset終了 -->
        {% csrf_token %}
        <button class="btn btn-{{ mysite.color }}" type="submit">コメントする</button>
        <a class="btn btn-{{ mysite.color }}" href="{% url 'blog:detail' post.pk %}" rel="nofollow">戻る</a>
    </form>

{% endblock %}

blog/templates/blog/contact_mail.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block meta_des %}Contact Mail{% endblock %}

{% block main %}
<div class="container">
    <h2 class="my-3 text-center">Contact Mail</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>DateTime</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody>
            {% for mail in mail_list %}
            <tr>
                <td>{{ mail.name }}</td>
                <td>{{ mail.created_at }}</td>
                <td><a href="{% url 'blog:contact_mail_detail' mail.id %}">{{ mail.get_text }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

blog/templates/blog/contact_mail_detail.html
{% extends 'blog/layout.html' %}
{% load static %}
{% block meta_des %}Contact Mail Detail{% endblock %}

{% block main %}
    <div class="container my-5">
        <div class="card">
            <div class="card-header">
                <h2>{{ mail.name }} -- {{ mail.email }}</h2>
            </div>
            <div class="card-body">
                {{ mail.text }}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/contact_me_form.html
{% extends "blog/main_layout.html" %}
{% load static %}
{% load blogfilter %}
{% block meta_des %}コンタクトページ{% endblock %}
{% block title %}コンタクトページ{% endblock %}

{% block content %}
    {{ form.non_field_errors }}
    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <p style="color: #ff2727;">{{ field.errors }}</p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button class="btn btn-lg btn-success" type="submit">
            送信
        </button>
    </form>
{% endblock %}

blog/templates/blog/layout.html
{% extends 'blog/base.html' %}
{% block layout %}

<!-- グローバルナビゲーション -->
{% include 'blog/widgets/nav.html' %}

<!-- ヘッダー -->
{% include 'blog/widgets/header.html' %}

<!-- メインコンテンツ -->
{% block main %}
{% endblock %}

<!-- フッター -->
{% include 'blog/widgets/footer.html' %}

{% endblock %}

blog/templates/blog/main_layout.html
{% extends 'blog/layout.html' %}

{% block main %}
    <div class="bg-light">
        <!-- main部分をより引き締める -->
        <div class="container">
            <div class="container">
                <div class="container">
                    {% block bread %}{% endblock %}
                    <div class="row">
                        <!-- 左側のメインコンテンツ -->
                        <main class="col-12 col-md-9">
                            {% block content %}
                            {% endblock %}
                        </main><!-- メインコンテンツ終了 -->

                        <!-- 右側のサイドバー -->
                        <aside class="col-12 col-md-3 ">

                            <!-- 自己紹介 -->
                            {% include 'blog/widgets/side_about.html' %}

                            <!-- カテゴリ一覧 -->
                            {% include 'blog/widgets/side_category.html' %}

                            <!-- タグ一覧 -->
                            {% include 'blog/widgets/side_tag.html' %}

                            {#                    <!-- リンク一覧 -->#}
                            {#                    {% include 'blog/widgets/side_link.html' %}#}

                            {#                    <!-- コメント一覧 -->#}
                            {#                    {% include 'blog/widgets/side_comment.html' %}#}

                            {% include 'blog/widgets/popular_post_list.html'  %}

                            <!-- 広告一覧 -->
                            {% for ad in ads %}
                                {{ ad.html | safe }}
                            {% endfor %}<!-- 広告一覧終了 -->

                        </aside><!-- /サイドバー終了 -->

                    </div><!-- /.row -->

                    <!-- 人気記事一覧 -->
{#                    <aside>#}
{#                        {% include 'blog/widgets/popular_post_list.html' %}#}
{#                    </aside>#}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/main_layout.html" %}
{% load static %}

{% block meta_des %}
  {{ post.get_description }}
{% endblock %}

{% block title %}{{post.title}} - {{ mysite.title }}{% endblock %}

{% block bread %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">記事一覧</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a></li>
    <li class="breadcrumb-item">{{ post.title }}</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
<!-- 目次部分 -->
<div id="toc"></div>

<!-- 記事詳細部分 -->
<article>
  {% include 'blog/widgets/detail_card.html' %}
</article>

<!-- コメント一覧 -->
<div id="comment-area">
  {% for comment in post.comment_set.all %}
    {% include 'blog/widgets/detail_comment.html' %}
  {% endfor %}
</div>

<div class="text-center my-5">
  <a class="btn btn-lg text-white" style="background: #f3e97a" href="{% url 'blog:comment' post.pk %}" rel="nofollow">コメントページへ</a>
</div>

{% endblock %}

{% block extrajs %}
<script src="{% static 'blog/js/toc.js' %}"></script>
{% endblock %}

blog/templates/blog/tag_list.html
{% extends "blog/main_layout.html" %}
{% load static %}
{% load blogfilter %}
{% block meta_des %}{{ mysite.title }}のタグ一覧ページです。{% endblock %}
{% block title %}タグ一覧 | {{ mysite.title }}{% endblock %}

{% block bread%}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">記事一覧</a></li>
    <li class="breadcrumb-item">タグ一覧</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
  {% for tag in tag_list %}
    <p><a href="{% url 'blog:tag' tag.name %}">{{ tag.name }}({{ tag.num_posts }})</a></p>
    <hr>
  {% endfor %}
{% endblock %}

blog/templates/blog/thank.html
{% extends 'blog/main_layout.html' %}
{% load static %}
{% block meta_des %}{% endblock %}

{% block title %}Thank You For Your Contact!{% endblock %}

{% block content %}
    <div class="container">
        <div>
            <h4 class="text-center my-5">コメントありがとうございます</h4>
        </div>
        <div class="row">
            <a class="btn col-md-3 d-block mx-auto" href="{% url 'blog:index' %}"
               style="background: #cce5ff; color: #00bbff">
                トップページへ
            </a>
        </div>
    </div>
{% endblock %}