blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .feeds import LatestEntriesFeed
from .sitemap import (
    PostSitemap, TagSitemap,
    CategorySitemap, StaticSitemap
)
app_name = 'blog'

sitemaps = {
    'post': PostSitemap,
    'category': CategorySitemap,
    'tag': TagSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),

    path('ping/', views.ping, name='ping'),

    path('alltag/', views.TagListView.as_view(), name='tag_list'),

    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),

    path('tag/<str:tag>/', views.TagView.as_view(), name='tag'),

    path('contact/', views.ContactMeCreateView.as_view(), name='contact'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('contact_mail/', views.ContactMailListView.as_view(), name='contact_mail'),
    path('contact_mail/<int:pk>', views.ContactMailDetailView.as_view(), name='contact_mail_detail'),

    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
    path('recomment/<int:pk>/', views.ReCommentCreateView.as_view(), name='recomment'),
    path('file_download/<int:pk>/', views.file_download, name='file_download'),

    path('private/', views.PostPrivateIndexView.as_view(), name='private'),

    path('latest/feed/', LatestEntriesFeed(), name='feed'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

core/urls.py
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path('home', views.home, name='home'),
    path('home/<int:community_id>/', views.real_home, name='real_home'),
    path('home/<int:community_id>/article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('home/<int:community_id>/article/<int:article_id>/edit', views.article_edit, name='article_edit'),
    path('article/<int:article_id>/delete', views.article_delete, name='article_delete'),
    path('home/<int:community_id>/create/', views.article_create, name='article_create'),

    path('home/article/<int:article_id>/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),

    path('my_article/', views.my_article, name='my_article'),

    path('community_manage/', views.community_manage, name='community_manage'),
    path('community_create/', views.community_create, name='community_create'),
    path('home/<int:community_id>/detail/', views.community_detail, name='community_detail'),
    path('home/<int:community_id>/edit/', views.community_edit, name='community_edit'),
    path('home/<int:community_id>/delete/', views.community_delete, name='community_delete'),

    path('community_search/', views.community_search, name='community_search'),
    path('home/<int:community_id>/follow', views.community_follow, name='community_follow'),
    path('home/<int:community_id>/user_manage/', views.community_user_manage, name='community_user_manage'),
    path('home/<int:community_id>/permitted_user_manage/', views.community_permitted_user_manage,
         name='community_permitted_user_manage'),
]

curation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import login, logout
from user_auth.views import signup, my_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),

    path('login/', login, kwargs={'template_name': 'user_auth/login.html'}, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
    path('my_page/', my_page, name='my_page'),
]

# 開発環境でのメディアファイルの配信設定
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

core/models.py
from django.db import models

# Create your models here.
from django.db import models
from user_auth.models import User
# Create your models here.


class Tag(models.Model):
    pass


class Community(models.Model):
    name = models.CharField('コミュニティ名', max_length=30)
    description = models.TextField('コミュニティの説明')
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    is_public = models.BooleanField('公開非公開設定', default=True)
    stand_by_user = models.ManyToManyField(User, verbose_name='承認待ちのユーザー', related_name='stand_by_user', blank=True)
    permitted_user = models.ManyToManyField(User, verbose_name='許可されたユーザー', related_name='permitted_user', blank=True)
    created_at = models.DateTimeField('作成日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時', auto_now=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField('記事名', max_length=30)
    body = models.TextField('内容')
    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_admin_user')
    thumbnail = models.ImageField('サムネイル', upload_to='media/', blank=True)
    community = models.ForeignKey(Community, on_delete=models.CASCADE, default=int)
    is_public = models.BooleanField('公開非公開設定', default=True)
    like_user = models.ManyToManyField(User, verbose_name='いいねしたユーザー', related_name='article_like_user',blank=True)
    created_at = models.DateTimeField('作成日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時', auto_now=True)

    def __str__(self):
        return self.title

    def summary(self):
        if len(self.body) < 150:
            return self.body
        else:
            return self.body[:150] + '...'


class Comment(models.Model):
    body = models.TextField('内容')
    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_admin_user')
    created_at = models.DateTimeField('投稿日時', auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comment_admin_article')

core/forms.py
from django import forms
from django.db.models import Q

from .models import Comment, Community, Article


class ArticleCommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (
            'body',
        )


class ArticleCreateForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            'title',
            'body',
            'thumbnail',
            'is_public',
        )


class ArticleEditForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            'title',
            'body',
            'thumbnail',
            'is_public',
        )


# 記事のタイトルか中身にキーワードを含むものを返す
def search_articles(keyword):
    return Article.objects.filter(Q(title__contains=keyword) | Q(body__contains=keyword))


class ArticleSearchForm(forms.ModelForm):
    search_word = forms.CharField(label='検索ワード')

    class Meta:
        model = Article
        fields = ()


class CommunityCreateForm(forms.ModelForm):

    class Meta:
        model = Community
        fields = (
            'name',
            'description',
        )


class CommunityEditForm(forms.ModelForm):

    class Meta:
        model = Community
        fields = (
            'name',
            'description',
        )

core/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

from .models import Article, Community, Comment
from user_auth.models import User
from .forms import (
    ArticleCommentForm, ArticleCreateForm, ArticleEditForm, CommunityCreateForm, CommunityEditForm, ArticleSearchForm,
    search_articles
)

# Create your views here.


def home(request):
    community_id = request.GET.get('community_id', 1)
    if not community_id:
        community_id = 1
    # community = get_object_or_404(Community, id=community_id)
    # articles = community.articles.order_by('-updated_at')

    # return render(request, 'core/home.html',
    #               {'community': community,
    #                'articles': articles})
    return HttpResponseRedirect(reverse('core:real_home', args=(community_id,)))


@login_required
def real_home(request, community_id):
    community = get_object_or_404(Community, id=community_id)
    permitted_communities = []
    admin_communities = []
    community_all = Community.objects.all()
    for com in community_all:
        if request.user in com.permitted_user.all():
            permitted_communities.append(com)
        if request.user.id == com.admin_id:
            admin_communities.append(com)

    articles = Article.objects.filter(community_id=community_id, is_public=True).order_by('-updated_at')
    # articles = community.articles.filter(is_public=True).order_by('-updated_at')

    article_search_form = ArticleSearchForm(request.GET)
    if article_search_form.is_valid():
        search_word = article_search_form.cleaned_data['search_word']
        articles = search_articles(search_word)

    params = request.GET.copy()
    if 'page' in params:
        page = params['page']
        del params['page']
    else:
        page = 1
    search_params = params.urlencode()

    paginator = Paginator(articles, 6)
    try:
        articles = paginator.page(page)
    except (PageNotAnInteger, EmptyPage):
        articles = paginator.page(1)

    return render(request, 'core/home.html',
                  {'community': community,
                   'articles': articles,
                   'permitted_communities': permitted_communities,
                   'admin_communities': admin_communities,
                   'article_search_form': article_search_form,
                   'search_params': search_params})


@login_required
def article_detail(request,community_id, article_id):
    article = get_object_or_404(Article, id=article_id)
    comments = Comment.objects.filter(article_id=article.id)
    if request.method == 'POST':
        form = ArticleCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.admin_id = request.user.id
            comment.article_id = article.id
            comment.save()

        return HttpResponseRedirect(reverse('core:article_detail', args=(community_id, article_id,)))
    else:
        comment_paginator = Paginator(comments, 10)
        page = request.GET.get('page')
        try:
            comments = comment_paginator.page(page)
        except (PageNotAnInteger, EmptyPage):
            comments = comment_paginator.page(1)

        form = ArticleCommentForm()
        return render(request, 'core/article_detail.html',
                  {'article': article,
                   'form': form,
                   'comments': comments,
                   'community_id': community_id})


@login_required
def article_create(request, community_id):
    community = get_object_or_404(Community, id=community_id)

    if request.method == 'POST':
        form = ArticleCreateForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.community_id = community_id
            article.admin_id = request.user.id
            article.save()

        return HttpResponseRedirect(reverse('core:real_home', args=(community_id,)))
    else:
        form = ArticleCreateForm()
        return render(request, 'core/article_create.html',
                      {'form': form,
                       'community_id': community_id})


@login_required
def article_edit(request, community_id, article_id):
    article = get_object_or_404(Article, id=article_id)
    if article.admin_id != request.user.id:
        error = '権限がありません'
        return render(request, 'core/error.html',
                      {'error': error})

    if request.method == 'POST':
        form = ArticleEditForm(request.POST, instance=article)
        if form.is_valid():
            form.save()

        return HttpResponseRedirect(reverse('core:article_detail', args=(community_id, article_id)))
    else:
        form = ArticleEditForm(instance=article)
        return render(request, 'core/article_edit.html',
                      {'form': form,
                       'article': article})


@login_required
def my_article(request):
    try:
        articles = Article.objects.filter(admin_id=request.user.id).order_by('-updated_at')
    except Article.DoesNotExist:
        raise Http404
    is_exists = articles.exists()

    paginator = Paginator(articles, 14)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except (PageNotAnInteger, EmptyPage):
        articles = paginator.page(1)

    return render(request, 'core/my_article.html',
                  {'articles': articles,
                   'is_exists': is_exists})


@login_required
@require_POST
def article_delete(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    article.delete()
    return HttpResponseRedirect(reverse('core:real_home',args=(article.community_id,)))


@login_required
def article_search(request):
    pass


@login_required
@require_POST
def comment_delete(request, article_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    article = get_object_or_404(Article, id=article_id)
    comment.delete()
    return HttpResponseRedirect(reverse('core:article_detail', args=(article.community_id, article_id,)))


@login_required
def community_manage(request):
    communities = Community.objects.filter(admin_id=request.user.id).order_by('name')
    is_exists = communities.exists()
    paginator = Paginator(communities, 8)
    page = request.GET.get('page')
    try:
        communities = paginator.page(page)
    except (PageNotAnInteger, EmptyPage):
        communities = paginator.page(1)

    return render(request, 'core/community_manage.html',
                  {'communities': communities,
                   'is_exists': is_exists})


@login_required
def community_create(request):
    if request.method == 'POST':
        form = CommunityCreateForm(request.POST)
        if form.is_valid():
            community = form.save(commit=False)
            community.admin_id = request.user.id
            community.save()

        return HttpResponseRedirect(reverse('core:community_manage'))
    else:
        form = CommunityCreateForm()
        return render(request, 'core/community_create.html',
                      {'form': form})


@login_required
def community_detail(request, community_id):
    community = get_object_or_404(Community, id=community_id)
    user = request.user
    if user in community.permitted_user.all():
        follow_status = 1  # フォロー済み
    elif user in community.stand_by_user.all():
        follow_status = 2  # 承認待ち
    else:
        follow_status = 3  # 未フォロー

    return render(request, 'core/community_detail.html',
                  {'community': community,
                   'follow_status': follow_status})


@login_required
def community_edit(request, community_id):
    community = get_object_or_404(Community, id=community_id)

    if request.method == 'POST':
        form = CommunityEditForm(request.POST, instance=community)
        if form.is_valid():
            form.save()

        return HttpResponseRedirect(reverse('core:community_detail', args=(community_id,)))
    else:
        form = CommunityEditForm(instance=community)
        return render(request, 'core/community_edit.html',
                      {'form': form,
                       'community': community})


@login_required
@require_POST
def community_delete(request, community_id):
    community = get_object_or_404(Community, id=community_id)
    community.delete()
    return HttpResponseRedirect(reverse('core:community_manage'))


@login_required
def community_search(request):
    communities = Community.objects.order_by('?')[:20]
    return render(request, 'core/community_search.html',
                  {'communities': communities})


@login_required
def community_follow(request, community_id):
    community = get_object_or_404(Community, id=community_id)
    if request.user in community.stand_by_user.all() or request.user in community.permitted_user.all():
        community.stand_by_user.remove(request.user)
        community.save()
    else:
        community.stand_by_user.add(request.user)
        community.save()
    return HttpResponseRedirect(reverse('core:community_detail',args=(community_id,)))


@login_required
def community_user_manage(request, community_id):
    community = get_object_or_404(Community, id=community_id)
    stand_by_users = community.stand_by_user.all()
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        if user_id:
            user = get_object_or_404(User, id=user_id)
            community.permitted_user.add(user)
            community.stand_by_user.remove(user)
            community.save()
        return HttpResponseRedirect(reverse('core:community_user_manage',kwargs={'community_id': community_id}))
    else:

core/templates/core/article_create.html
{% extends 'core/base.html' %}
{% load core_tag %}
{% load widget_tweaks %}
{% block title %}Article Create{% endblock %}

{% block content %}

    <div class="container bg-light">
        <h2 class="text-center mt-5">まとめ作成</h2>
        <form action="{% url 'core:article_create' community_id %}" method="post">
            {% csrf_token %}
            {% for filed in form.visible_fields %}
                <div class="form-group">
                    <label for="field.id_for_label">{{ filed.label_tag }}</label>
                    {{ filed |add_class:"form-control" }}
                </div>
            {% endfor %}
            <div class="form-group w-25 mx-auto">
                <input class="form-control btn btn-info " type="submit" value="投稿する">
            </div>
        </form>
    </div>

{% endblock %}

core/templates/core/article_detail.html
{% extends 'core/base.html' %}
{% load core_tag %}
{% load widget_tweaks %}
{% block title %}Article Detail{% endblock %}

{% block content %}

    <div class="container bg-light mb-5">
        <div class="article-header row header">
            <div class="col-9">
                <h1 class="text-center">タイトル: {{ article.title }}</h1><br/>
                <h5>タグ</h5>

            </div>
            <div class="col-3">
                {% if user.id == article.admin.id %}
                    <a href="{% url 'core:article_edit' community_id article.id %}"
                       class="btn btn-info mt-3">編集する</a><br/>
                {% endif %}
                投稿者: {{ aritlce.admin }}<br/>
                (作成日時) {{ article.created_at }}<br/>
                (最終更新日時) {{ article.updated_at }}
            </div>
        </div>
        <hr/>

        <div class="article-body">
            {{ article.body |linebreaksbr | urlize | url_target_blank }}
        </div>
        <hr/>

        <div class="comment-form">
            <h3>コメントする</h3>
            <form method="post" action="{% url 'core:article_detail' community_id article.id %}">
                {% for filed in form.visible_fields %}
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="filed.id_for_label">{{ filed.label_tag }}</label>
                        {{ filed |add_class:'form-control w-50' }}
                    </div>
                {% endfor %}
                <div class="form-group">
                    <input class="btn btn-info" type="submit" value="コメント"/>
                </div>
            </form>
            <hr/>
        </div>

        <div class="comments">
            <h2>コメント一覧</h2>
            {% for comment in comments %}
                <div class="mt-3 border-bottom">
                    {% if comment.admin_id == user.id %}
                        <div class="float-right">
                            <button class="btn btn-danger btn-sm btn-round d-block" data-toggle="modal"
                                    data-target="#deleteComment">
                                削除
                            </button>
                            <!-- Modal Core -->
                            <div class="modal fade" id="deleteComment" tabindex="-1" role="dialog"
                                 aria-labelledby="deleteComment" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                                &times;
                                            </button>
                                            <h4 class="modal-title" id="myModalLabel">確認</h4>
                                        </div>
                                        <div class="modal-body">
                                            本当に削除しますか？
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default btn-simple"
                                                    data-dismiss="modal">キャンセル
                                            </button>
                                            <form action="{% url 'core:comment_delete' article.id comment.id %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-danger btn-simple" type="submit" value="削除">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    {% endif %}
                    <h5>{{ forloop.counter }}: {{ comment.admin.username }} ({{ comment.created_at }})<br/></h5>
                    {{ comment.body | linebreaksbr |urlize | url_target_blank }}
                </div>
            {% endfor %}
            <!--                             ページネーション                                    -->
            <nav class="justify-content-center d-block col-6 mx-auto my-4 py-3" aria-label="Page navigation">
                <ul class="pagination pagination-primary w-25 mx-auto">
                    {% if comments.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ comments.previous_page_number }}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">
                                <span aria-hidden="true"><i class="fa fa-angle-double-left"
                                                            aria-hidden="true"></i></span>
                            </a>
                        </li>
                    {% endif %}

                    {% for link_page in comments.paginator.page_range %}
                        {% if link_page == comments.number %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{ link_page }}">{{ link_page }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ link_page }}">{{ link_page }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if comments.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ comments.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                    {% endif %}
                </ul>
            </nav>

        </div>
    </div>



{% endblock %}

core/templates/core/article_edit.html
{% extends 'core/base.html' %}
{% load core_tag %}
{% load widget_tweaks %}
{% block title %}Article Create{% endblock %}

{% block content %}

    <div class="container bg-light">
        <h2 class="text-center mt-5">編集</h2>
        <form action="{% url 'core:article_edit' article.community_id article.id %}" method="post">
            {% csrf_token %}
            {% for filed in form.visible_fields %}
                <div class="form-group">
                    <label for="field.id_for_label">{{ filed.label_tag }}</label>
                    {{ filed |add_class:"form-control" }}
                </div>
            {% endfor %}
            <div class="form-group w-25 mx-auto">
                <input class="form-control btn btn-info " type="submit" value="編集する">
            </div>
        </form>
        <!-- Button trigger modal -->
        <div class="row">
            <div class="col-12">
                <div class="col-3 mx-auto">
                    <button class="btn btn-danger btn-round d-block mx-auto" data-toggle="modal"
                            data-target="#deleteArticle">
                        削除する
                    </button>

                    <!-- Modal Core -->
                    <div class="modal fade" id="deleteArticle" tabindex="-1" role="dialog"
                         aria-labelledby="deleteArticle" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                        &times;
                                    </button>
                                    <h4 class="modal-title" id="myModalLabel">確認</h4>
                                </div>
                                <div class="modal-body">
                                    本当に削除しますか？
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">
                                        キャンセル
                                    </button>
                                    <form action="{% url 'core:article_delete' article.id %}" method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-danger btn-simple" type="submit" value="削除">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

core/templates/core/base.html
{% load static %}
{% load core_tag %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
{#    <link rel="stylesheet" href="{% static 'css/core.css' %}">#}
    {#    <link rel="stylesheet" href="{% static 'css/now-ui-kit/css/bootstrap.min.css' %}">#}
    <link rel="stylesheet" href="{% static 'now_ui_kit/css/now-ui-kit.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{#    <link rel="stylesheet" href="{% static 'now-ui-kit/css/demo.css' %}">#}
    {#    <link rel="shortcut icon" href="{% static 'css/now-ui-kit/img/favicon.png' %}">#}


    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-light sticky-top" style="background-color: #add8e6;">
    <a class="navbar-brand" href="{% url 'my_page' %}">{{ user.username }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li>
                <a class="nav-link" href="{% url 'core:home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}" class="nav-item">ログアウト</a></li>
        {% else %}
            <li><a href="{% url 'login' %}" class="nav-item text-dark">ログイン</a></li>
        {% endif %}
    </div>
</nav>

{% block content %}

{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>

</body>
</html>

core/templates/core/error.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block title %}Error Page{% endblock %}

{% block content %}

    <div class="container">
        <div class="error_msg text-center">
            {{ error }}
        </div>
    </div>

{% endblock %}