blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .feeds import LatestEntriesFeed
from .sitemap import (
    PostSitemap, TagSitemap,
    CategorySitemap, StaticSitemap
)
app_name = 'blog'

sitemaps = {
    'post': PostSitemap,
    'category': CategorySitemap,
    'tag': TagSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),

    path('ping/', views.ping, name='ping'),

    path('alltag/', views.TagListView.as_view(), name='tag_list'),

    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),

    path('tag/<str:tag>/', views.TagView.as_view(), name='tag'),

    path('contact/', views.ContactMeCreateView.as_view(), name='contact'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('contact_mail/', views.ContactMailListView.as_view(), name='contact_mail'),
    path('contact_mail/<int:pk>', views.ContactMailDetailView.as_view(), name='contact_mail_detail'),

    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
    path('recomment/<int:pk>/', views.ReCommentCreateView.as_view(), name='recomment'),
    path('file_download/<int:pk>/', views.file_download, name='file_download'),

    path('private/', views.PostPrivateIndexView.as_view(), name='private'),

    path('latest/feed/', LatestEntriesFeed(), name='feed'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

core/urls.py
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path('home', views.home, name='home'),
    path('home/<int:community_id>/', views.real_home, name='real_home'),
    path('home/<int:community_id>/article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('home/<int:community_id>/article/<int:article_id>/edit', views.article_edit, name='article_edit'),
    path('article/<int:article_id>/delete', views.article_delete, name='article_delete'),
    path('home/<int:community_id>/create/', views.article_create, name='article_create'),

    path('home/article/<int:article_id>/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),

    path('my_article/', views.my_article, name='my_article'),

    path('community_manage/', views.community_manage, name='community_manage'),
    path('community_create/', views.community_create, name='community_create'),
    path('home/<int:community_id>/detail/', views.community_detail, name='community_detail'),
    path('home/<int:community_id>/edit/', views.community_edit, name='community_edit'),
    path('home/<int:community_id>/delete/', views.community_delete, name='community_delete'),

    path('community_search/', views.community_search, name='community_search'),
    path('home/<int:community_id>/follow', views.community_follow, name='community_follow'),
    path('home/<int:community_id>/user_manage/', views.community_user_manage, name='community_user_manage'),
    path('home/<int:community_id>/permitted_user_manage/', views.community_permitted_user_manage,
         name='community_permitted_user_manage'),
]

curation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import login, logout
from user_auth.views import signup, my_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),

    path('login/', login, kwargs={'template_name': 'user_auth/login.html'}, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
    path('my_page/', my_page, name='my_page'),
]

# 開発環境でのメディアファイルの配信設定
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

user_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    class Meta(AbstractUser.Meta):
        db_table = 'user'
        swappable = 'AUTH_USER_MODEL'

    def get_full_name(self):
        return self.last_name + ' ' + self.first_name

user_auth/forms.py
from django import forms
from user_auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
            'password1',  # password
            'password2',  # password_confirm
        )

user_auth/views.py
from django.shortcuts import render,redirect
from user_auth.forms import UserForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
# Create your views here.


def signup(request):

    if request.method == 'POST':
        form = UserForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            password2 = form.cleaned_data.get('password2')
            if not password1 == password2:
                return redirect('signup')
            form.save()
            user = authenticate(username=username, password=password1)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('my_page')
    else:
        form = UserForm

    return render(request, 'user_auth/signup.html',
                  {'form': form})


def my_page(request):
    return render(request, 'user_auth/my_page.html',
                  {'profile_user': request.user})

user_auth/templates/user_auth/base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'now_ui_kit/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'now_ui_kit/css/now-ui-kit.css' %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-sm navbar-light sticky-top" style="background-color: #add8e6;">
    <a class="navbar-brand" href="{% url 'my_page' %}">{{ user.username }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}" class="nav-item">ログアウト</a></li>
        {% else %}
            <li><a href="{% url 'login' %}" class="nav-item text-dark">ログイン</a></li>
        {% endif %}
    </div>
</nav>

{% block content %}

{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>

</body>
</html>

user_auth/templates/user_auth/login.html
{% extends 'user_auth/base.html' %}
{% load widget_tweaks %}
{% block title %}ログイン{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="w-25 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {% for field in form.visible_fields %}
                            <label for="field.id_for_label">{{ field.label_tag }}</label>
                            {{ field |add_class:"form-control" }}
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <input class="btn btn-info form-control d-block col-6 mx-auto" type="submit" value="ログイン">
                    </div>
                </form>
                <div class="">
                    <a href="{% url 'signup' %}" class="btn btn-success d-block col-6 mx-auto">登録画面へ</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

user_auth/templates/user_auth/my_page.html
{% extends 'user_auth/base.html' %}

{% block title %}My page{% endblock %}

{% block content %}

    <div class="container">
        <div class="text-center mt-4">
            <ul>
                <li>ユーザー名: {{ user.username }}</li>
            </ul>
        </div>

        <div class="list-group col-8 mx-auto">
            <li class="list-group-item"><a href="{% url 'core:my_article' %}">自分の記事</a></li>
            <li class="list-group-item"><a href="{% url 'core:community_manage' %}">コミュニティ管理</a></li>
            <li class="list-group-item"><a href="{% url 'core:community_create' %}">コミュニティ作成</a></li>
            <li class="list-group-item"><a href="{% url 'core:community_search' %}">コミュニティを探す</a></li>
        </div>
    </div>


{% endblock %}

user_auth/templates/user_auth/signup.html
{% extends 'user_auth/base.html' %}
{% load widget_tweaks %}

{% block title %}Signup{% endblock %}

{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="w-25 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {# {% render_field form.password1 class="form-control" placeholder=form.password1.label %}#}
                        {# {% render_field form.password2 class="form-control" placeholder=form.password2.label %}#}
                        {% for field in form.visible_fields %}
                            <label for="field.id_for_field">{{ field.label_tag }}</label>
                            {{ field |add_class:"form-control" }}
                            {% for error in field.errors %}
                                <span class="help-block text-danger">{{ error }}</span>
                            {% endfor %}
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <input class="form-control btn btn-success d-block col-6 mx-auto" type="submit" value="登録">
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}